//! # distill
//!
//! Deterministic `SessionCard` extraction from completed tasks.
//!
//! ## Design Philosophy
//!
//! A 100,000-token terminal session can be reduced to 250–400 high-signal
//! tokens with **zero LLM calls** by applying deterministic heuristics:
//!
//! - **File paths** are extracted by regex from event content and labels.
//! - **Exit codes** come from structured metadata JSON or terminal output patterns.
//! - **Commands** are pulled from `EventSource::Terminal` events.
//! - **Decisions** come from `EventSource::Manual` + `EventSource::Mcp` events,
//!   which are already curated human/AI annotations.
//!
//! This approach is:
//! - **Instantaneous** — no network round-trips
//! - **Free** — no API token cost
//! - **Deterministic** — same inputs always produce the same card
//! - **Private** — no content leaves the machine
//!
//! For complex, unstructured long-context sessions, an optional LLM pass
//! (Ollama / local model) can be added in a future phase without changing
//! the `SessionCard` interface.
//!
//! ## Token Estimate
//!
//! A `SessionCard` serializes to approximately 250–400 tokens (300–500 words),
//! compared to a raw event dump of 50,000–200,000 tokens. This is a **99.5%+
//! token reduction** for the AI context window.

use std::collections::HashSet;

use regex::Regex;
use serde::{Deserialize, Serialize};

use crate::{ContextEvent, EventSource, Task, TaskStatus};

// =============================================================================
// SessionCard
// =============================================================================

/// The outcome of a completed or abandoned task session.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionResult {
    Completed,
    Abandoned,
}

/// A structured command result extracted from terminal events.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandResult {
    /// The command that was run (e.g. "cargo test -p ctxd")
    pub cmd: String,
    /// Exit code if determinable from output or metadata (0 = success)
    pub exit_code: Option<i32>,
}

/// Distilled summary of a completed developer task session.
///
/// Generated by [`extract_session_card`] from a `Task` + its `ContextEvent`s.
/// Stored in `tasks.summary` as JSON and returned by the MCP `distill_task` tool.
///
/// A `SessionCard` serializes to ~250–400 tokens — vs. 50,000–200,000 tokens
/// for the raw event stream.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionCard {
    /// Task UUID — links back to the `tasks` table.
    pub task_id: String,

    /// Task name / human goal (from `ctx task start <name>`).
    pub goal: String,

    /// Wall-clock duration of the task.
    pub duration_secs: i64,

    /// Unique file paths mentioned across all events.
    /// Ordered by first appearance.
    pub files_touched: Vec<String>,

    /// Terminal commands with their exit codes (when determinable).
    pub commands_verified: Vec<CommandResult>,

    /// Human and AI-authored decisions/notes captured during the session.
    pub decisions: Vec<String>,

    /// Whether the task completed successfully or was abandoned.
    pub result: SessionResult,

    /// Rough token estimate for context budget allocation.
    pub token_estimate: usize,
}

impl SessionCard {
    /// Serialize to a compact JSON string for storage in `tasks.summary`.
    pub fn to_json(&self) -> String {
        serde_json::to_string(self).unwrap_or_else(|_| "{}".to_string())
    }

    /// Deserialize from JSON stored in `tasks.summary`.
    pub fn from_json(s: &str) -> Option<Self> {
        serde_json::from_str(s).ok()
    }

    /// Format the card as a human-readable markdown string for CLI display
    /// and MCP context injection.
    pub fn to_markdown(&self) -> String {
        use std::fmt::Write as _;
        let mut out = String::new();

        let _ = writeln!(out, "## Session: {}", self.goal);
        let res_str = match self.result {
            SessionResult::Completed => "✅ Completed",
            SessionResult::Abandoned => "❌ Abandoned",
        };
        let dur_str = format_duration(self.duration_secs);
        let _ = writeln!(out, "**Duration:** {dur_str}  **Result:** {res_str}\n");

        if !self.files_touched.is_empty() {
            out.push_str("**Files Touched:**\n");
            for f in &self.files_touched {
                let _ = writeln!(out, "- `{f}`");
            }
            out.push('\n');
        }

        if !self.commands_verified.is_empty() {
            out.push_str("**Commands Verified:**\n");
            for c in &self.commands_verified {
                let status = match c.exit_code {
                    Some(0) => "✅".to_string(),
                    Some(code) => format!("❌ (exit {code})"),
                    None => "—".to_string(),
                };
                let _ = writeln!(out, "- `{}` {status}", c.cmd);
            }
            out.push('\n');
        }

        if !self.decisions.is_empty() {
            out.push_str("**Key Decisions:**\n");
            for d in &self.decisions {
                let _ = writeln!(out, "- {d}");
            }
        }

        out
    }
}

fn format_duration(secs: i64) -> String {
    if secs < 60 {
        format!("{secs}s")
    } else if secs < 3600 {
        let mins = secs / 60;
        let rem_secs = secs % 60;
        format!("{mins}m {rem_secs}s")
    } else {
        let hours = secs / 3600;
        let mins = (secs % 3600) / 60;
        format!("{hours}h {mins}m")
    }
}

// =============================================================================
// Extraction Engine
// =============================================================================

/// Lazily compiled regexes used by the extractor.
struct Extractors {
    file_path: Regex,
    exit_code_pattern: Regex,
    metadata_exit_code: Regex,
}

impl Extractors {
    fn new() -> Self {
        Self {
            // Match common source file paths in output
            // Captures: path/to/file.ext where ext is a known code extension
            file_path: Regex::new(
                r#"(?:^|[\s`'"(])([a-zA-Z0-9_./\-]+\.(?:rs|ts|js|tsx|jsx|py|go|toml|json|yaml|yml|md|sql|sh|lock|env))(?:[\s`'",;:)]|$)"#
            ).expect("file_path regex must compile"),

            // Match "exit code: N" patterns in terminal output
            exit_code_pattern: Regex::new(
                r"(?i)exit(?:ed)?\s+(?:with\s+)?(?:code\s+)?[:\s]?\s*(\d+)"
            ).expect("exit_code_pattern regex must compile"),

            // Match exit_code field in JSON metadata
            metadata_exit_code: Regex::new(
                r#""exit_code"\s*:\s*(-?\d+)"#
            ).expect("metadata_exit_code regex must compile"),
        }
    }
}

/// Extract a structured [`SessionCard`] from a completed or abandoned task
/// and its associated events.
///
/// This function is deterministic and makes zero network calls.
///
/// # Arguments
///
/// - `task` — The completed/abandoned `Task` from the database.
/// - `events` — All `ContextEvent`s linked to `task.id`, ordered by timestamp ascending.
///
/// # Returns
///
/// A `SessionCard` that can be stored in `tasks.summary` and used for
/// AI context injection via the MCP `distill_task` tool.
pub fn extract_session_card(task: &Task, events: &[ContextEvent]) -> SessionCard {
    let ex = Extractors::new();

    let duration_secs = task.duration().num_seconds();

    let result = match task.status {
        TaskStatus::Abandoned => SessionResult::Abandoned,
        _ => SessionResult::Completed,
    };

    // ── File path extraction ─────────────────────────────────────────────────
    let mut files_seen: HashSet<String> = HashSet::new();
    let mut files_touched: Vec<String> = Vec::new();

    for event in events {
        let text = format!("{} {}", event.label, event.content);
        for cap in ex.file_path.captures_iter(&text) {
            if let Some(path) = cap.get(1) {
                let p = path.as_str().to_string();
                // Skip noise: test binary paths, target dir, lock files
                let is_lock = std::path::Path::new(&p)
                    .extension()
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("lock"));
                if !p.contains("target/")
                    && !p.contains(".git/")
                    && !is_lock
                    && files_seen.insert(p.clone())
                {
                    files_touched.push(p);
                }
            }
        }
    }

    // ── Terminal command extraction ──────────────────────────────────────────
    let mut commands_verified: Vec<CommandResult> = Vec::new();

    for event in events.iter().filter(|e| e.source == EventSource::Terminal) {
        let cmd = event.label.trim().to_string();
        if cmd.is_empty() {
            continue;
        }

        // Try to extract exit code from metadata JSON first
        let exit_code = event
            .metadata
            .as_ref()
            .and_then(|m| m["exit_code"].as_i64().map(|c| c as i32))
            .or_else(|| {
                // Try from structured metadata JSON string in content
                if let Some(meta_str) = event.metadata.as_ref().map(ToString::to_string) {
                    ex.metadata_exit_code
                        .captures(&meta_str)
                        .and_then(|c| c.get(1))
                        .and_then(|m| m.as_str().parse::<i32>().ok())
                } else {
                    None
                }
            })
            .or_else(|| {
                // Last resort: scan content for "exit code: N" patterns
                ex.exit_code_pattern
                    .captures(&event.content)
                    .and_then(|c| c.get(1))
                    .and_then(|m| m.as_str().parse::<i32>().ok())
            });

        commands_verified.push(CommandResult { cmd, exit_code });
    }

    // Deduplicate consecutive identical commands (e.g. repeated `cargo check`)
    commands_verified.dedup_by(|a, b| a.cmd == b.cmd);

    // ── Decision extraction ──────────────────────────────────────────────────
    let decisions: Vec<String> = events
        .iter()
        .filter(|e| {
            matches!(e.source, EventSource::Manual | EventSource::Mcp)
                && !e.content.trim().is_empty()
        })
        .map(|e| e.content.trim().to_string())
        .collect();

    // ── Token estimate ───────────────────────────────────────────────────────
    // Rough: 1 token ≈ 4 chars. Card content is goal + files + cmds + decisions.
    let card_text_len = task.name.len()
        + files_touched.iter().map(|f| f.len() + 4).sum::<usize>()
        + commands_verified
            .iter()
            .map(|c| c.cmd.len() + 10)
            .sum::<usize>()
        + decisions.iter().map(|d| d.len() + 2).sum::<usize>();
    let token_estimate = (card_text_len / 4).max(50);

    SessionCard {
        task_id: task.id.to_string(),
        goal: task.name.clone(),
        duration_secs,
        files_touched,
        commands_verified,
        decisions,
        result,
        token_estimate,
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ContextEvent, EventSource, Task, TaskStatus};

    fn make_task(name: &str, status: TaskStatus) -> Task {
        let mut t = Task::new(name);
        t.status = status;
        t
    }

    fn terminal_event(label: &str, content: &str) -> ContextEvent {
        ContextEvent::new(EventSource::Terminal, label, content)
    }

    fn manual_event(content: &str) -> ContextEvent {
        ContextEvent::new(EventSource::Manual, "note", content)
    }

    #[test]
    fn test_empty_events_produces_card() {
        let task = make_task("refactor auth", TaskStatus::Completed);
        let card = extract_session_card(&task, &[]);
        assert_eq!(card.goal, "refactor auth");
        assert!(card.files_touched.is_empty());
        assert!(card.commands_verified.is_empty());
        assert!(card.decisions.is_empty());
        assert_eq!(card.result, SessionResult::Completed);
    }

    #[test]
    fn test_abandoned_task_result() {
        let task = make_task("wip feature", TaskStatus::Abandoned);
        let card = extract_session_card(&task, &[]);
        assert_eq!(card.result, SessionResult::Abandoned);
    }

    #[test]
    fn test_file_path_extraction_from_content() {
        let task = make_task("fix auth", TaskStatus::Completed);
        let events = vec![terminal_event(
            "cargo check",
            "error in crates/ctxd/src/auth.rs:42\nwarning in Cargo.toml",
        )];
        let card = extract_session_card(&task, &events);
        assert!(
            card.files_touched.iter().any(|f| f.contains("auth.rs")),
            "auth.rs should be extracted, got: {:?}",
            card.files_touched
        );
        assert!(
            card.files_touched.iter().any(|f| f.contains("Cargo.toml")),
            "Cargo.toml should be extracted, got: {:?}",
            card.files_touched
        );
    }

    #[test]
    fn test_exit_code_from_metadata() {
        let task = make_task("run tests", TaskStatus::Completed);
        let mut event = terminal_event("cargo test", "running 5 tests\nok");
        event.metadata = Some(serde_json::json!({ "exit_code": 0 }));
        let card = extract_session_card(&task, &[event]);
        assert_eq!(card.commands_verified.len(), 1);
        assert_eq!(card.commands_verified[0].exit_code, Some(0));
    }

    #[test]
    fn test_exit_code_from_content_pattern() {
        let task = make_task("run tests", TaskStatus::Completed);
        let event = terminal_event("cargo test", "test result: FAILED\nexited with code 101");
        let card = extract_session_card(&task, &[event]);
        assert_eq!(card.commands_verified[0].exit_code, Some(101));
    }

    #[test]
    fn test_decisions_extracted_from_manual_events() {
        let task = make_task("design session", TaskStatus::Completed);
        let events = vec![
            manual_event("Use HMAC-SHA256 with 0600 token storage"),
            manual_event("Defer vector search to Phase 6"),
        ];
        let card = extract_session_card(&task, &events);
        assert_eq!(card.decisions.len(), 2);
        assert!(card.decisions[0].contains("HMAC-SHA256"));
        assert!(card.decisions[1].contains("Phase 6"));
    }

    #[test]
    fn test_duplicate_commands_deduped() {
        let task = make_task("iterative build", TaskStatus::Completed);
        let events = vec![
            terminal_event("cargo check", "ok"),
            terminal_event("cargo check", "ok"), // duplicate
            terminal_event("cargo test", "passed"),
        ];
        let card = extract_session_card(&task, &events);
        // "cargo check" should appear only once
        let cargo_check_count = card
            .commands_verified
            .iter()
            .filter(|c| c.cmd == "cargo check")
            .count();
        assert_eq!(cargo_check_count, 1);
    }

    #[test]
    fn test_token_estimate_reasonable() {
        let task = make_task("implement ring buffer", TaskStatus::Completed);
        let events = vec![
            terminal_event("cargo test", "ok"),
            manual_event("Use mpsc channel with 1000 capacity"),
        ];
        let card = extract_session_card(&task, &events);
        // Should be between 50 and 10,000 tokens for a small session
        assert!(card.token_estimate >= 50);
        assert!(card.token_estimate < 10_000);
    }

    #[test]
    fn test_target_dir_files_excluded() {
        let task = make_task("build", TaskStatus::Completed);
        let event = terminal_event(
            "cargo build",
            "Compiling target/debug/ctxd\nCompiling crates/ctxd/src/main.rs",
        );
        let card = extract_session_card(&task, &[event]);
        assert!(
            !card.files_touched.iter().any(|f| f.contains("target/")),
            "target/ paths should be excluded, got: {:?}",
            card.files_touched
        );
    }

    #[test]
    fn test_session_card_markdown_format() {
        let task = make_task("implement JWT auth", TaskStatus::Completed);
        let events = vec![
            terminal_event("cargo test -p ctxd", "test result: ok. 5 passed"),
            manual_event("Used HMAC-SHA256 signing"),
        ];
        let card = extract_session_card(&task, &events);
        let md = card.to_markdown();
        assert!(md.contains("implement JWT auth"));
        assert!(md.contains("Completed"));
        assert!(md.contains("HMAC-SHA256"));
    }

    #[test]
    fn test_session_card_json_roundtrip() {
        let task = make_task("roundtrip test", TaskStatus::Completed);
        let card = extract_session_card(&task, &[]);
        let json = card.to_json();
        let recovered = SessionCard::from_json(&json).expect("must deserialize");
        assert_eq!(recovered.goal, card.goal);
        assert_eq!(recovered.task_id, card.task_id);
    }
}
